/* 
**  mod_compat.c -- Apache sample compat module
**  [Autogenerated via ``apxs -n compat -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_compat.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /compat in as follows:
**
**    #   httpd.conf
**    LoadModule compat_module modules/mod_compat.so
**    <Location /compat>
**    SetHandler compat
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /compat and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/compat 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_compat.c
*/ 

#define CORE_PRIVATE

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include "apache_logging.h"

#include <dlfcn.h>

static int module_init(apr_pool_t *p, apr_pool_t *plog, apr_pool_t *ptemp, server_rec *s) {
// ap_hook_post_config 会被调用2次

#ifdef AP_SQ_MAIN_STATE
    // httpd 2.4.x 保证只在第二次调用module_init时进行初始化操作
    if (ap_state_query(AP_SQ_MAIN_STATE) == AP_SQ_MS_CREATE_PRE_CONFIG)
        return OK;
#else
// httpd 2.2.x 保证只在第二次调用module_init时进行初始化操作
    void *data;
    const char *userdata_key = "pang_module_init";

    /* initialize_module() will be called twice, and if it's a DSO
     * then all static data from the first call will be lost. Only
     * set up our static data on the second call. */
    apr_pool_userdata_get(&data, userdata_key, s->process->pool);
    if (!data) {
        apr_pool_userdata_set((const void *)1, userdata_key,
                               apr_pool_cleanup_null, s->process->pool);
        return OK;
    }
#endif

    //Do your module init job.

    return OK;
}

static void child_init(apr_pool_t* pool, server_rec* s) {
    
    //Do your init job while child process startup.

    return;
}

/* The sample content handler */
static int request_handler(request_rec *r) {
    if (  !r->handler ) {
        return DECLINED;
    } 
    if( strcmp(r->handler, "compat") ) {
        return DECLINED;
    }
    r->content_type = "text/html";
    
    if (!r->header_only) {
        char* content = "The sample page from mod_compat.c\n";
        ap_rputs(content, r);
    }
    return OK;
}

static void compat_register_hooks(apr_pool_t *p) {
    ap_hook_post_config(module_init, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_child_init(child_init, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_handler(request_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA compat_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    compat_register_hooks  /* register hooks                      */
};

static __attribute__((constructor)) void so_on_load() {
    ap_module_symbol_t symbol_core_module = ap_prelinked_module_symbols[0];
    compat_module.magic = symbol_core_module.modp->magic;
    compat_module.version = symbol_core_module.modp->version;
}
